### ISSUE TITLE
v4.0.1

### ISSUE THREAD

**Issue by zifredder** [syncloud/grocy#2]
Hi @cyberb !
Sorry to bother you once more, but I am uncertain.
The current grocy version is 4.0.1 -- what's the best way to update?
Setting `local version = "4.0.1";` in `.drone.jsonnet`?
According to the [grocy readme](https://github.com/grocy/grocy#how-to-update), there is an update script that could be run, so this might work, too, but I guess building it from the beginning with the desired version is better, correct?

I am unsure about the workflow. This would be my approach:
1. Change the version in `.drone.jsonnet` and commit.
2. Wait for the build pipeline to complete.
3. If the build succeeded and all tests passed: Make a pull request.
4. If you accept the pull request, the app will be updated.

Would that work?
Thank you for your help! :star:

**Comment by cyberb** [comment]
Yes that is exactly how it works!
I think we build only bull requests, so do not wait and create a PR right away.

**Comment by zifredder** [comment]
Fast and helpful as always, thanks! The build for master is running, created a PR for stable.

**Comment by cyberb** [comment]
hey, I forgot you are the admin of this repo :)
Let me fix master branch with your change but not related to your change, looks like some tests need to be updated, I will let you know here.

**Comment by cyberb** [comment]
interesting, 4.0.1 requires php 8.1 which is difficult to package on arm32 I think this architecture is slowly dying. 
@zifredder are you on arm32?
there is a chance that grocy will not upgrade to 4.0.1 on arm32 and will continue on amd64/arm64

**Comment by zifredder** [comment]
Ah I see. Yeah, I'm running a pretty old Raspberry Pi 2 with arm32. But I have been thinking about upgrading the hardware for quite a while, so I think I will do that in the course of the next weeks.

**Comment by cyberb** [comment]
Pushed 4.0.1 to the store, arm32 will stay on the old version.
